version: '3.4'

services:
  paymentgateway-api:
    image: paymentgateway-api:0.0.1
    build:
      context: ./src/PaymentGateway
      dockerfile: PaymentGateway.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=postgres;Username=postgres;Password=example
      - OAuthSettings__Authority=http://host.docker.internal:5555
      - AcquiringBankSettings__BaseUrl=http://host.docker.internal:5050
    ports:
      - "5000:80"

  identityserver:
    image: identityserver:0.0.1
    build:
      context: ./src
      dockerfile: IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AppSettings__IssuerUri=http://host.docker.internal:5555
    ports:
      - "5555:80"


  acquiringbank-api-mock:
    image: acquiringbank-api-mock:0.0.1
    build:
      context: ./src
      dockerfile: AcquiringBank.Api.Mock/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5050:80"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db-data: